// Translit — automatic keyboard layout switcher (Punto Switcher style).
//
// Lives in the status bar. Watches keystrokes via a CGEventTap, buffers the
// current word as *keycodes*, and when a word separator arrives, reads the
// buffer through both the English and Russian layouts. Each reading is scored
// against precomputed bigram log-probability tables (see Bigrams.swift,
// generated by train/train.js). If the alternative layout's reading is
// significantly more plausible than what was actually typed, the word is
// erased, the system layout is switched, and the word is retyped — the
// separator key is delivered after the fix, so it works even for Enter.
//
// Undo: pressing Backspace as the very next key after an auto-fix reverts it
// verbatim and remembers the word as an exception (never auto-fixed again).
//
// Resource profile: fully event-driven — no timers while running (a short
// retry timer exists only until Accessibility is granted). Scoring is a few
// dozen integer additions per word. Tables are static arrays in the binary.
//
// Build:   swift build -c release   (or ./build.sh to produce Translit.app)
// Install: ./install.sh — copies to ~/Applications, sets up the LaunchAgent.
// Requires: Accessibility permission; the Russian layout enabled in macOS.

import Foundation
import AppKit
import Carbon.HIToolbox
import Darwin

// MARK: - Constants

let bundleID = "com.arsidian.translit"
let singletonLockPath = "/tmp/translit.singleton.lock"

let minWordLength = 3
/// Switch when the other layout's reading beats the typed one by at least this
/// much per character (scaled log2 units; 4 = 1 bit/char). Picked from the
/// validation gap percentiles printed by train/train.js.
let switchMargin = 4.0
/// Never switch TO a reading that is itself implausible (garbage in both
/// layouts). Average scaled log2 per transition; -32 = 8 bits per char.
let plausibilityFloor = -32.0
/// Pause after TISSelectInputSource before retyping: layout changes are
/// applied asynchronously and early keystrokes would use the old layout.
let layoutSettleMicroseconds: UInt32 = 60_000
/// Pause between synthetic keystrokes — some apps drop events posted too fast.
let keystrokeGapMicroseconds: UInt32 = 2_000
/// Marks our own synthetic events so the tap callback passes them through.
let syntheticEventMarker: Int64 = 0x7472_616E // "tran"

let enabledDefaultsKey = "enabled"
let soundDefaultsKey = "soundOnFix"
let autoUpdateDefaultsKey = "autoUpdate"
let excludedAppsDefaultsKey = "excludedApps"
let exceptionWordsDefaultsKey = "exceptionWords"
let defaultExcludedApps = ["com.apple.Terminal", "com.googlecode.iterm2"]

let appVersion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "dev"

func log(_ message: String) {
    let ts = ISO8601DateFormatter().string(from: Date())
    FileHandle.standardError.write("[\(ts)] \(message)\n".data(using: .utf8)!)
}

/// Single instance via exclusive flock; the descriptor stays open for life.
func acquireSingletonLock() -> Bool {
    let fd = open(singletonLockPath, O_CREAT | O_RDWR, 0o600)
    guard fd >= 0 else { return true }
    return flock(fd, LOCK_EX | LOCK_NB) == 0
}

// MARK: - Settings

enum Settings {
    private static func boolDefaultingTrue(_ key: String) -> Bool {
        let d = UserDefaults.standard
        if d.object(forKey: key) == nil { return true }
        return d.bool(forKey: key)
    }

    static var enabled: Bool {
        get { boolDefaultingTrue(enabledDefaultsKey) }
        set { UserDefaults.standard.set(newValue, forKey: enabledDefaultsKey) }
    }

    /// Play a click when a word gets auto-fixed (audible feedback that the
    /// text just changed behind the cursor).
    static var soundOnFix: Bool {
        get { boolDefaultingTrue(soundDefaultsKey) }
        set { UserDefaults.standard.set(newValue, forKey: soundDefaultsKey) }
    }

    /// Reinstall automatically when the dotfiles checkout has a newer VERSION.
    static var autoUpdate: Bool {
        get { boolDefaultingTrue(autoUpdateDefaultsKey) }
        set { UserDefaults.standard.set(newValue, forKey: autoUpdateDefaultsKey) }
    }

    static var excludedApps: Set<String> {
        get {
            let d = UserDefaults.standard
            guard let list = d.stringArray(forKey: excludedAppsDefaultsKey) else {
                return Set(defaultExcludedApps)
            }
            return Set(list)
        }
        set { UserDefaults.standard.set(Array(newValue).sorted(), forKey: excludedAppsDefaultsKey) }
    }

}

// MARK: - Keyboard layouts

/// Keycode→character maps for the English and Russian layouts, plus layout
/// switching. All TIS calls happen on the main thread (TIS is not threadsafe);
/// the built maps are immutable afterwards.
final class Layouts {
    let enSource: TISInputSource
    let ruSource: TISInputSource
    let enSourceID: String
    let ruSourceID: String
    /// Lowercase character produced by each keycode (0..<128) with no modifiers.
    let enChars: [Character?]
    let ruChars: [Character?]
    /// Alphabet index per keycode for the scorer: 1-based letter index,
    /// -1 = the key does not produce a letter in that alphabet.
    let enLetterIndex: [Int]
    let ruLetterIndex: [Int]

    private(set) var current: Current = .other
    enum Current { case en, ru, other }

    init?() {
        precondition(Thread.isMainThread)
        guard let en = TISCopyCurrentASCIICapableKeyboardLayoutInputSource()?.takeRetainedValue(),
              let enID = Layouts.sourceID(en) else {
            log("⚠️ No ASCII-capable keyboard layout found.")
            return nil
        }
        guard let ru = Layouts.findRussianLayout(), let ruID = Layouts.sourceID(ru) else {
            log("⚠️ No enabled Russian keyboard layout — enable one in System Settings → Keyboard.")
            return nil
        }
        enSource = en
        ruSource = ru
        enSourceID = enID
        ruSourceID = ruID
        enChars = Layouts.keycodeMap(for: en)
        ruChars = Layouts.keycodeMap(for: ru)
        enLetterIndex = Layouts.letterIndexes(chars: enChars, alphabet: enAlphabet)
        ruLetterIndex = Layouts.letterIndexes(chars: ruChars, alphabet: ruAlphabet)
        refreshCurrent()
    }

    /// Re-reads which layout is active. Main thread only.
    func refreshCurrent() {
        precondition(Thread.isMainThread)
        guard let src = TISCopyCurrentKeyboardInputSource()?.takeRetainedValue(),
              let id = Layouts.sourceID(src) else {
            current = .other
            return
        }
        switch id {
        case enSourceID: current = .en
        case ruSourceID: current = .ru
        default: current = .other
        }
    }

    /// Selects the given layout. Main thread only.
    func select(_ which: Current) {
        precondition(Thread.isMainThread)
        switch which {
        case .en: TISSelectInputSource(enSource)
        case .ru: TISSelectInputSource(ruSource)
        case .other: return
        }
        current = which
    }

    /// What a word turns into on the other layout: "b" → «и», "еру" → "the".
    /// Direction is inferred from the alphabet. "?" marks unmappable chars.
    func converted(_ word: String) -> String {
        let isCyrillic = word.contains { ("а"..."я").contains($0) || $0 == "ё" }
        let source = isCyrillic ? ruChars : enChars
        let target = isCyrillic ? enChars : ruChars
        var result = ""
        for ch in word.lowercased() {
            if let code = source.firstIndex(where: { $0 == ch }), let out = target[code] {
                result.append(out)
            } else {
                result.append("?")
            }
        }
        return result
    }

    private static func sourceID(_ s: TISInputSource) -> String? {
        guard let ptr = TISGetInputSourceProperty(s, kTISPropertyInputSourceID) else { return nil }
        return Unmanaged<CFString>.fromOpaque(ptr).takeUnretainedValue() as String
    }

    /// First *enabled* keyboard layout whose language list contains "ru".
    private static func findRussianLayout() -> TISInputSource? {
        let filter = [kTISPropertyInputSourceType as String: kTISTypeKeyboardLayout as String]
        guard let list = TISCreateInputSourceList(filter as CFDictionary, false)?
            .takeRetainedValue() as? [TISInputSource] else { return nil }
        for src in list {
            guard let ptr = TISGetInputSourceProperty(src, kTISPropertyInputSourceLanguages),
                  let langs = Unmanaged<CFArray>.fromOpaque(ptr).takeUnretainedValue() as? [String]
            else { continue }
            if langs.contains("ru") { return src }
        }
        return nil
    }

    /// keycode → character with no modifiers, via UCKeyTranslate.
    private static func keycodeMap(for source: TISInputSource) -> [Character?] {
        var map = [Character?](repeating: nil, count: 128)
        guard let raw = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return map
        }
        let data = Unmanaged<CFData>.fromOpaque(raw).takeUnretainedValue() as Data
        let kbdType = UInt32(LMGetKbdType())
        data.withUnsafeBytes { buf in
            guard let layout = buf.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self)
            else { return }
            for code in 0..<128 {
                var dead: UInt32 = 0
                var length = 0
                var chars = [UniChar](repeating: 0, count: 4)
                let status = UCKeyTranslate(layout, CGKeyCode(code), UInt16(kUCKeyActionDown),
                                            0, kbdType, OptionBits(kUCKeyTranslateNoDeadKeysBit),
                                            &dead, chars.count, &length, &chars)
                guard status == noErr, length == 1,
                      let scalar = UnicodeScalar(chars[0]),
                      !CharacterSet.controlCharacters.contains(scalar) else { continue }
                map[code] = Character(scalar)
            }
        }
        return map
    }

    private static func letterIndexes(chars: [Character?], alphabet: String) -> [Int] {
        var indexOf: [Character: Int] = [:]
        for (i, ch) in alphabet.enumerated() { indexOf[ch] = i + 1 }
        return chars.map { ch in
            guard let ch = ch else { return -1 }
            return indexOf[ch] ?? -1
        }
    }
}

// MARK: - User dictionary (rules & exceptions)

/// Two plain-text word lists in ~/.config/translit (a symlink into the
/// dotfiles repo when installed from it, so edits sync between machines):
///   rules.txt      — REAL words, restored whenever their wrong-layout
///                    typing appears: «и» rescues "b ", "the" rescues «еру».
///                    Bypasses statistics and the minimum length; direction
///                    is implied by the entry's alphabet.
///   exceptions.txt — as-typed readings never to fix; Backspace-undo
///                    appends here.
/// Files are watched with dispatch sources and reloaded on change — edit in
/// any editor mid-flight, no restart needed.
///
/// Format v2: rules hold canonical words (people naturally write «в», not
/// "d"). Files without the v2 marker are migrated once by converting each
/// entry through the layout maps.
final class UserDict {
    static let dirPath = NSHomeDirectory() + "/.config/translit"
    static let rulesPath = dirPath + "/rules.txt"
    static let exceptionsPath = dirPath + "/exceptions.txt"
    static let formatMarker = "# translit-rules v2"

    /// Canonical default rules, seeded on machines without a dictionary and
    /// merged in when migrating a v1 file. Mirrors .config/translit/rules.txt
    /// in the dotfiles repo — keep the two in sync.
    /// Note: Russian words ending in б/ю/ж/э/х/ъ are useless as rules — their
    /// final key reads as English punctuation and is split off before the
    /// dictionary lookup — so they are deliberately absent.
    static let defaultRuleWords = [
        // Russian, 1–3 letters (fix en→ru)
        "а", "в", "и", "к", "о", "с", "у", "я",
        "на", "за", "не", "но", "по", "до", "от", "из", "он", "мы", "ты", "вы",
        "же", "ли", "бы", "да", "ни", "ну", "то", "та", "те", "ту", "со", "во",
        "ей", "ее", "им",
        "так", "как", "что", "все", "это", "вот", "кто", "где", "там", "тут",
        "они", "она", "оно", "нас", "вас", "ним", "ней", "его", "ему", "чем",
        "том", "той", "мне", "мой", "моя", "наш", "ваш", "сам", "нет", "был",
        "два", "три", "сто", "лет", "год", "раз",
        // English (fix ru→en)
        "the", "is", "if", "in", "it", "on", "at", "or", "of", "to", "no",
        "not", "and", "for", "ok", "be", "me", "we", "he", "my", "by", "do",
        "go", "so", "up", "us", "am", "an", "as",
    ]

    private static var rulesHeader: String {
        """
        \(formatMarker)
        # Translit rules: real words that are always restored when typed in the
        # wrong layout. Cyrillic entries fix en→ru («и» rescues "b "), Latin
        # entries fix ru→en ("the" rescues «еру»). One word per line, # for
        # comments, case-insensitive. The app reloads this file on change.
        """
    }

    private static var defaultRulesContent: String {
        rulesHeader + "\n\n" + defaultRuleWords.joined(separator: "\n") + "\n"
    }

    private(set) var rules: Set<String> = []
    private(set) var exceptions: Set<String> = []
    private var watchers: [DispatchSourceFileSystemObject] = []
    private var reloadPending = false
    /// Fired on the main queue after any change — from the UI or the files.
    var onChange: (() -> Void)?

    /// `converting` maps a word to its other-layout reading (Layouts.converted)
    /// and powers the one-time v1 → v2 file migration; nil skips migration.
    init(converting: ((String) -> String)? = nil) {
        ensureFiles()
        migrateLegacyExceptions()
        migrateRulesFormat(converting: converting)
        load()
    }

    /// True when the config dir is a symlink whose target is missing — the
    /// dotfiles checkout it pointed at was moved or never existed on this
    /// machine. Every read and write then fails silently, leaving the app
    /// with an empty dictionary and no visible reason.
    private static func repairBrokenSymlink() {
        let fm = FileManager.default
        guard let attrs = try? fm.attributesOfItem(atPath: dirPath),
              attrs[.type] as? FileAttributeType == .typeSymbolicLink else { return }
        let target = (try? fm.destinationOfSymbolicLink(atPath: dirPath)) ?? "?"
        let resolved = target.hasPrefix("/")
            ? target
            : (dirPath as NSString).deletingLastPathComponent + "/" + target
        var isDir: ObjCBool = false
        if fm.fileExists(atPath: resolved, isDirectory: &isDir), isDir.boolValue { return }
        log("⚠️ \(dirPath) points at a missing \(resolved) — replacing it with a real folder.")
        try? fm.removeItem(atPath: dirPath)
    }

    private func ensureFiles() {
        let fm = FileManager.default
        Self.repairBrokenSymlink()
        do {
            try fm.createDirectory(atPath: Self.dirPath, withIntermediateDirectories: true)
        } catch {
            log("⚠️ Cannot create \(Self.dirPath): \(error.localizedDescription)")
        }
        let exceptionsHeader = """
        # Translit exceptions: never auto-fix these words. One word per line,
        # spelled as typed (the reading in the layout that was active).
        # Backspace right after an auto-fix reverts it and appends the word here.
        """
        if !fm.fileExists(atPath: Self.rulesPath) {
            do {
                try Self.defaultRulesContent.write(toFile: Self.rulesPath, atomically: true,
                                                   encoding: .utf8)
                log("Seeded \(Self.rulesPath) with \(Self.defaultRuleWords.count) default rules.")
            } catch {
                log("⚠️ Cannot write \(Self.rulesPath): \(error.localizedDescription)")
            }
        }
        if !fm.fileExists(atPath: Self.exceptionsPath) {
            try? (exceptionsHeader + "\nеще\n").write(toFile: Self.exceptionsPath,
                                                      atomically: true, encoding: .utf8)
        }
    }

    /// v1 rules were spelled "as typed in the wrong layout" ("b", "yt",
    /// "еру") — counter-intuitive, and under v2 matching they would fire in
    /// the WRONG direction. Convert every old entry to its canonical word,
    /// merge with the defaults, and stamp the marker.
    private func migrateRulesFormat(converting: ((String) -> String)?) {
        guard let text = try? String(contentsOfFile: Self.rulesPath, encoding: .utf8),
              !text.contains(Self.formatMarker) else { return }
        guard let convert = converting else { return }
        var words = Self.defaultRuleWords
        var seen = Set(words)
        for line in text.split(separator: "\n") {
            let word = line.trimmingCharacters(in: .whitespaces).lowercased()
            if word.isEmpty || word.hasPrefix("#") { continue }
            let canonical = convert(word)
            let keep = canonical.contains("?") ? word : canonical
            if seen.insert(keep).inserted { words.append(keep) }
        }
        let out = Self.rulesHeader + "\n\n" + words.joined(separator: "\n") + "\n"
        try? out.write(toFile: Self.rulesPath, atomically: true, encoding: .utf8)
        log("Migrated rules.txt to v2: \(words.count) canonical word(s).")
    }

    /// Exceptions used to live in UserDefaults — move them into the file once.
    private func migrateLegacyExceptions() {
        let d = UserDefaults.standard
        guard let legacy = d.stringArray(forKey: exceptionWordsDefaultsKey), !legacy.isEmpty else {
            d.removeObject(forKey: exceptionWordsDefaultsKey)
            return
        }
        let existing = Self.parse(Self.exceptionsPath)
        for word in legacy where !existing.contains(word.lowercased()) {
            Self.append(word.lowercased(), to: Self.exceptionsPath)
        }
        d.removeObject(forKey: exceptionWordsDefaultsKey)
        log("Migrated \(legacy.count) exception(s) from UserDefaults to exceptions.txt.")
    }

    /// (Re)reads both files and re-arms the watchers — editors replace files
    /// on save, so the old descriptors go stale after every change.
    private func load() {
        rules = Self.parse(Self.rulesPath)
        exceptions = Self.parse(Self.exceptionsPath)
        // An unreadable or unwritable config dir used to leave the app with
        // no rules at all and no hint why. Short words are exactly what the
        // statistics cannot decide, so fall back to the built-in set: worst
        // case the file stays broken, but corrections still work.
        if rules.isEmpty {
            // Try to heal the file itself; fall back to memory if even that
            // fails, so a broken config can never disarm the dictionary.
            do {
                try Self.defaultRulesContent.write(toFile: Self.rulesPath, atomically: true,
                                                   encoding: .utf8)
                rules = Self.parse(Self.rulesPath)
                log("\(Self.rulesPath) had no rules — reseeded with the defaults.")
            } catch {
                log("⚠️ \(Self.rulesPath) has no rules and cannot be rewritten " +
                    "(\(error.localizedDescription)) — using the built-in set in memory.")
            }
            if rules.isEmpty { rules = Set(Self.defaultRuleWords) }
        }
        log("Dictionary: \(rules.count) rule(s), \(exceptions.count) exception(s).")
        watchers.forEach { $0.cancel() }
        watchers = [Self.dirPath, Self.rulesPath, Self.exceptionsPath].compactMap { watch($0) }
        onChange?()
    }

    private static func parse(_ path: String) -> Set<String> {
        guard let text = try? String(contentsOfFile: path, encoding: .utf8) else { return [] }
        var words = Set<String>()
        for line in text.split(separator: "\n") {
            let word = line.trimmingCharacters(in: .whitespaces).lowercased()
            if word.isEmpty || word.hasPrefix("#") { continue }
            words.insert(word)
        }
        return words
    }

    func addException(_ word: String) {
        let lower = word.lowercased()
        guard !exceptions.contains(lower) else { return }
        exceptions.insert(lower)
        Self.append(lower, to: Self.exceptionsPath)
        onChange?()
    }

    /// True when the rules file cannot be written — the UI says so instead of
    /// pretending an edit was saved.
    var storageIsWritable: Bool {
        FileManager.default.isWritableFile(atPath: Self.rulesPath)
    }

    func addRule(_ word: String) {
        let lower = word.lowercased()
        guard !lower.isEmpty, !rules.contains(lower) else { return }
        rules.insert(lower)
        Self.append(lower, to: Self.rulesPath)
        onChange?()
    }

    func removeRule(_ word: String) {
        let lower = word.lowercased()
        guard rules.remove(lower) != nil else { return }
        Self.removeLine(lower, from: Self.rulesPath)
        onChange?()
    }

    func removeException(_ word: String) {
        let lower = word.lowercased()
        guard exceptions.remove(lower) != nil else { return }
        Self.removeLine(lower, from: Self.exceptionsPath)
        onChange?()
    }

    private static func append(_ line: String, to path: String) {
        if !FileManager.default.fileExists(atPath: path) {
            FileManager.default.createFile(atPath: path, contents: nil)
        }
        guard let handle = FileHandle(forWritingAtPath: path) else { return }
        defer { try? handle.close() }
        handle.seekToEndOfFile()
        handle.write((line + "\n").data(using: .utf8)!)
    }

    /// Drops the word's line, keeping comments and everything else intact.
    private static func removeLine(_ word: String, from path: String) {
        guard let text = try? String(contentsOfFile: path, encoding: .utf8) else { return }
        let kept = text.split(separator: "\n", omittingEmptySubsequences: false)
            .filter { $0.trimmingCharacters(in: .whitespaces).lowercased() != word }
            .joined(separator: "\n")
        try? kept.write(toFile: path, atomically: true, encoding: .utf8)
    }

    private func watch(_ path: String) -> DispatchSourceFileSystemObject? {
        let fd = open(path, O_EVTONLY)
        guard fd >= 0 else { return nil }
        let source = DispatchSource.makeFileSystemObjectSource(
            fileDescriptor: fd, eventMask: [.write, .extend, .rename, .delete], queue: .main)
        source.setEventHandler { [weak self] in self?.scheduleReload() }
        source.setCancelHandler { close(fd) }
        source.resume()
        return source
    }

    /// Debounces editor save bursts (atomic saves fire several events).
    private func scheduleReload() {
        guard !reloadPending else { return }
        reloadPending = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
            self?.reloadPending = false
            self?.load()
        }
    }
}

// MARK: - Scoring

/// Average scaled log2 probability per bigram transition of the buffer read
/// through one alphabet, or nil when any key is not a letter there.
func scoreReading(_ codes: [CGKeyCode], letterIndex: [Int], table: [Int8], n: Int) -> Double? {
    var sum = 0
    var prev = 0
    for code in codes {
        let cur = letterIndex[Int(code)]
        if cur < 0 { return nil }
        sum += Int(table[prev * n + cur])
        prev = cur
    }
    sum += Int(table[prev * n + 0])
    return Double(sum) / Double(codes.count + 1)
}

// MARK: - Engine

/// One pressed key as stored in the word buffer.
struct Key {
    let code: CGKeyCode
    let shift: Bool
}

/// A just-applied auto-fix, kept so an immediate Backspace can revert it.
struct Correction {
    /// The fixable token, as typed — replayed by keycode in the new layout.
    let coreKeys: [Key]
    /// Word-final punctuation as it read in the ORIGINAL layout ("flight," —
    /// the comma); retyped verbatim as unicode after the fix, because its
    /// keycode would produce a different character in the new layout.
    let trailingText: String
    /// Core + trailing keys — undo replays these in the original layout.
    let originalKeys: [Key]
    let separator: Key
    let originalLayout: Layouts.Current
    let fixedLayout: Layouts.Current
    /// What the reverted word reads as in its original layout — goes to the
    /// exception list on undo.
    let originalWord: String
}

final class Engine {
    static var shared: Engine!

    let layouts: Layouts
    private var tap: CFMachPort?
    private var buffer: [Key] = []
    private var tainted = false   // digits/Option chars seen — do not touch this word
    private var lastCorrection: Correction?
    /// A fix is being applied asynchronously; incoming events pass through
    /// untouched meanwhile (the on-screen text is in flux anyway).
    private var applyingFix = false
    /// Recent tap-disabled-by-timeout timestamps — the thrash detector.
    private var tapDisabledTimes: [Date] = []
    /// The thrash breaker tripped; the tap stays down until the revival
    /// timer (or the user, or a wake) re-arms it.
    private(set) var tapSuspended = false
    private var revivalTimer: Timer?
    /// Fired on suspend/revive so the status bar can update its icon.
    var onStateChange: (() -> Void)?
    private var frontAppID: String = ""
    private let enN = enAlphabet.count + 1
    private let ruN = ruAlphabet.count + 1
    let dict: UserDict

    /// Notifies the UI layer (status bar) that state worth showing changed.
    var onActivity: ((String) -> Void)?

    init(layouts: Layouts) {
        self.layouts = layouts
        self.dict = UserDict(converting: { layouts.converted($0) })
    }

    // MARK: Lifecycle

    /// Creates the event tap. Returns false when Accessibility is missing.
    func start() -> Bool {
        precondition(Thread.isMainThread)
        let mask: CGEventMask =
            (1 << CGEventType.keyDown.rawValue) |
            (1 << CGEventType.leftMouseDown.rawValue) |
            (1 << CGEventType.rightMouseDown.rawValue) |
            (1 << CGEventType.otherMouseDown.rawValue)
        guard let tap = CGEvent.tapCreate(
            tap: .cgSessionEventTap,
            place: .headInsertEventTap,
            options: .defaultTap,
            eventsOfInterest: mask,
            callback: { _, type, event, _ in
                Engine.shared.handle(type: type, event: event)
            },
            userInfo: nil
        ) else { return false }
        self.tap = tap
        let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0)
        CFRunLoopAddSource(CFRunLoopGetMain(), source, .commonModes)
        CGEvent.tapEnable(tap: tap, enable: true)

        observeContextChanges()
        log("Event tap active.")
        return true
    }

    /// Re-arms the tap and clears the thrash history. Called by the revival
    /// timer, on wake from sleep, and from the menu.
    func reviveTap() {
        tapDisabledTimes.removeAll()
        tapSuspended = false
        if let tap = tap { CGEvent.tapEnable(tap: tap, enable: true) }
        onStateChange?()
        log("Event tap re-armed.")
    }

    /// What is keeping corrections from working right now, in human terms.
    /// nil = everything is fine.
    func currentStatus() -> String? {
        if tapSuspended { return "Перехват приостановлен после сбоев — оживёт сам" }
        if IsSecureEventInputEnabled() {
            let culprit = Engine.secureInputCulprit().map { " — \($0)" } ?? ""
            return "Пауза: защищённый ввод\(culprit)"
        }
        return nil
    }

    /// The process holding secure input, per the window server session.
    /// Helps find the app that "ate" corrections (a password field left
    /// focused, a stuck loginwindow after unlock, etc.).
    static func secureInputCulprit() -> String? {
        guard let info = CGSessionCopyCurrentDictionary() as? [String: Any],
              let pid = info["kCGSSessionSecureInputPID"] as? Int else { return nil }
        let name = NSRunningApplication(processIdentifier: pid_t(pid))?.localizedName
        return name.map { "\($0)" } ?? "процесс \(pid)"
    }

    private func observeContextChanges() {
        // Frontmost app changes: the on-screen text no longer matches the buffer.
        let wsCenter = NSWorkspace.shared.notificationCenter
        wsCenter.addObserver(forName: NSWorkspace.didActivateApplicationNotification,
                             object: nil, queue: .main) { [weak self] note in
            guard let self = self else { return }
            let app = note.userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication
            self.frontAppID = app?.bundleIdentifier ?? ""
            self.reset()
            // The icon dims in excluded apps — tell the status bar to re-look.
            self.onStateChange?()
        }
        frontAppID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? ""

        // Sleep can leave the tap disabled — re-arm on wake.
        wsCenter.addObserver(forName: NSWorkspace.didWakeNotification,
                             object: nil, queue: .main) { [weak self] _ in
            self?.reset()
            self?.reviveTap()
        }

        // Manual layout switches: the buffer's "as typed" reading changes meaning.
        DistributedNotificationCenter.default().addObserver(
            forName: Notification.Name(kTISNotifySelectedKeyboardInputSourceChanged as String),
            object: nil, queue: .main
        ) { [weak self] _ in
            self?.layouts.refreshCurrent()
            self?.reset()
        }
    }

    // MARK: Event handling (main thread — the tap source lives on the main run loop)

    private func reset() {
        buffer.removeAll(keepingCapacity: true)
        tainted = false
    }

    func handle(type: CGEventType, event: CGEvent) -> Unmanaged<CGEvent>? {
        let pass: Unmanaged<CGEvent>? = Unmanaged.passUnretained(event)

        // macOS disables taps on secure input transitions (normal — just
        // re-arm) and when a callback stalls (timeout — count it). If the tap
        // keeps dying by timeout, blindly resurrecting it turns the whole
        // system's keyboard into a slideshow: cool down for a minute instead,
        // then revive automatically.
        if type == .tapDisabledByUserInput {
            if let tap = tap, !tapSuspended { CGEvent.tapEnable(tap: tap, enable: true) }
            return pass
        }
        if type == .tapDisabledByTimeout {
            tapDisabledTimes = tapDisabledTimes.filter { $0.timeIntervalSinceNow > -60 }
            tapDisabledTimes.append(Date())
            log("Event tap disabled by timeout (\(tapDisabledTimes.count) in the last minute).")
            if tapDisabledTimes.count > 5 {
                tapSuspended = true
                onStateChange?()
                log("⚠️ Tap keeps stalling — corrections paused for 60 s, then auto-revive.")
                revivalTimer?.invalidate()
                revivalTimer = Timer.scheduledTimer(withTimeInterval: 60,
                                                    repeats: false) { [weak self] _ in
                    self?.revivalTimer = nil
                    self?.reviveTap()
                }
                return pass
            }
            if let tap = tap { CGEvent.tapEnable(tap: tap, enable: true) }
            return pass
        }

        // Our own synthetic events must never be reprocessed.
        if event.getIntegerValueField(.eventSourceUserData) == syntheticEventMarker {
            return pass
        }

        if type != .keyDown {
            // Any mouse click: caret probably moved — the buffer is stale.
            reset()
            lastCorrection = nil
            return pass
        }

        // While synthetic events are being posted, real keystrokes interleave
        // with a text state that is mid-rewrite — stay out of the way.
        if applyingFix { return pass }

        let code = CGKeyCode(event.getIntegerValueField(.keyboardEventKeycode))
        let flags = event.flags

        // Command/Control chords are hotkeys, not text.
        if flags.contains(.maskCommand) || flags.contains(.maskControl) {
            reset()
            lastCorrection = nil
            return pass
        }

        // Backspace right after an auto-fix reverts it; swallow the keystroke.
        // The revert itself runs async — the tap callback must never block.
        if code == 51, let correction = lastCorrection {
            lastCorrection = nil
            applyingFix = true
            DispatchQueue.main.async { [weak self] in
                self?.undo(correction)
                self?.applyingFix = false
            }
            return nil
        }
        lastCorrection = nil

        if code == 51 { // Backspace edits the tail of the buffered word
            if !buffer.isEmpty { buffer.removeLast() }
            return pass
        }

        guard code < 128 else { reset(); return pass }

        let enLetter = layouts.enLetterIndex[Int(code)] > 0
        let ruLetter = layouts.ruLetterIndex[Int(code)] > 0

        if enLetter || ruLetter {
            // Option-modified letters produce different characters — taint.
            if flags.contains(.maskAlternate) { tainted = true }
            if buffer.count >= 64 { tainted = true }
            buffer.append(Key(code: code, shift: flags.contains(.maskShift)))
            return pass
        }

        if isSeparator(code) {
            let word = buffer
            let wasTainted = tainted
            reset()
            if !wasTainted, !word.isEmpty,
               let correction = decideFix(word: word,
                                          separator: Key(code: code,
                                                         shift: flags.contains(.maskShift))) {
                // Swallow the separator and apply the fix asynchronously: the
                // callback returns immediately, so system-wide key delivery
                // never stalls (a blocking callback here used to freeze input).
                applyingFix = true
                DispatchQueue.main.async { [weak self] in
                    guard let self = self else { return }
                    self.applyFix(correction)
                    self.lastCorrection = correction
                    self.applyingFix = false
                }
                return nil // the separator is retyped as part of the fix
            }
            return pass
        }

        // Digits and everything else: part of the token, but makes it untouchable.
        tainted = true
        return pass
    }

    /// Word separators: keys that produce a letter in neither layout.
    /// The separator is replayed by *keycode* after a fix, so a key whose
    /// character differs between layouts (`/` is `.` in Russian) still yields
    /// what the user meant: no fix → original char, fix → target-layout char.
    private func isSeparator(_ code: CGKeyCode) -> Bool {
        switch code {
        case 49, 36, 76, 48: return true // Space, Return, keypad Enter, Tab
        default: break
        }
        let i = Int(code)
        if layouts.enLetterIndex[i] > 0 || layouts.ruLetterIndex[i] > 0 { return false }
        guard let en = layouts.enChars[i], layouts.ruChars[i] != nil else { return false }
        // A digit ends no word — "word2" is one token (and never auto-fixed).
        if en.isNumber { return false }
        return true
    }

    // MARK: Decision & fix

    /// Pure decision, no side effects — safe to call from the tap callback.
    /// Dictionary rules force a fix bypassing statistics and the minimum
    /// length (short words like «и»/«не» are statistically undecidable);
    /// exceptions veto everything.
    private func decideFix(word: [Key], separator: Key) -> Correction? {
        guard Settings.enabled else { return nil }
        guard !Settings.excludedApps.contains(frontAppID) else { return nil }
        // Password fields enable secure input; never touch those.
        guard !IsSecureEventInputEnabled() else { return nil }
        return decide(word: word, separator: separator, current: layouts.current)
    }

    /// The decision itself, free of environment checks so `--test` can run
    /// exactly what the engine runs (a separate test-only reimplementation
    /// used to drift from this one). `explanation` receives a human-readable
    /// trace of why the verdict came out the way it did.
    func decide(word: [Key], separator: Key, current: Layouts.Current,
                explanation: ((String) -> Void)? = nil) -> Correction? {
        guard current == .en || current == .ru else {
            explanation?("active layout is neither en nor ru — nothing to do")
            return nil
        }
        let target: Layouts.Current = current == .en ? .ru : .en

        // Keys at the word's tail that produce no letter in the CURRENT
        // layout are word-final punctuation of the on-screen text, not part
        // of the token: the comma key is a Russian б, so "flight," used to
        // read as "impossible English" and lose to garbage Russian by
        // default. Judge the core only; the tail is retyped verbatim.
        let ownLetterIndex = current == .en ? layouts.enLetterIndex : layouts.ruLetterIndex
        var coreKeys = word
        var trailingKeys: [Key] = []
        while let last = coreKeys.last, ownLetterIndex[Int(last.code)] <= 0 {
            trailingKeys.insert(last, at: 0)
            coreKeys.removeLast()
        }
        guard !coreKeys.isEmpty else {
            explanation?("the token is punctuation only")
            return nil
        }

        let ownWord = readWord(coreKeys, current: current)
        guard !dict.exceptions.contains(ownWord.lowercased()) else {
            explanation?("\"\(ownWord)\" is in exceptions.txt — never fixed")
            return nil
        }

        // Rules hold canonical words: the fix fires when its RESULT is a
        // listed word («и» listed → "b" typed in en gets fixed to «и»).
        let fixedWord = readWord(coreKeys, current: target)
        if dict.rules.contains(fixedWord.lowercased()) {
            explanation?("\"\(fixedWord)\" is a rule word — fixed regardless of scores")
        } else {
            guard coreKeys.count >= minWordLength else {
                explanation?("no rule for \"\(fixedWord)\" and the word is shorter than " +
                             "\(minWordLength) letters — statistics can't decide, left alone")
                return nil
            }
            let codes = coreKeys.map { $0.code }
            let enScore = scoreReading(codes, letterIndex: layouts.enLetterIndex,
                                       table: enBigrams, n: enN)
            let ruScore = scoreReading(codes, letterIndex: layouts.ruLetterIndex,
                                       table: ruBigrams, n: ruN)
            let (own, other) = current == .en ? (enScore, ruScore) : (ruScore, enScore)

            guard let otherScore = other, otherScore >= plausibilityFloor else {
                explanation?("the other reading is impossible or implausible — left alone")
                return nil
            }
            if let ownScore = own, otherScore - ownScore < switchMargin {
                explanation?(String(format: "scores too close (own %.1f vs other %.1f, " +
                                            "need +%.0f) — left alone",
                                    ownScore, otherScore, switchMargin))
                return nil
            }
            explanation?("statistics: \"\(fixedWord)\" wins clearly")
        }

        let ownMap = current == .en ? layouts.enChars : layouts.ruChars
        let trailingText = String(trailingKeys.compactMap { ownMap[Int($0.code)] })
        return Correction(coreKeys: coreKeys, trailingText: trailingText,
                          originalKeys: word, separator: separator,
                          originalLayout: current, fixedLayout: target,
                          originalWord: ownWord)
    }

    private func readWord(_ word: [Key], current: Layouts.Current) -> String {
        let map = current == .en ? layouts.enChars : layouts.ruChars
        return String(word.compactMap { map[Int($0.code)] })
    }

    /// Erases the word, switches layout, retypes word + separator.
    /// The separator was swallowed, so only the word itself is on screen.
    /// Runs asynchronously on the main queue, never inside the tap callback.
    private func applyFix(_ correction: Correction) {
        postBackspaces(correction.originalKeys.count)
        layouts.select(correction.fixedLayout)
        usleep(layoutSettleMicroseconds)
        replay(correction.coreKeys)
        typeText(correction.trailingText)
        replay([correction.separator])
        if Settings.soundOnFix { NSSound(named: "Pop")?.play() }
        log("Fixed \"\(correction.originalWord)\" → " +
            (correction.fixedLayout == .ru ? "ru" : "en"))
        onActivity?(correction.originalWord)
    }

    /// Reverts a fix: erases the retyped word + separator, restores the
    /// original layout, retypes the original keys, remembers the exception.
    private func undo(_ correction: Correction) {
        // On screen: core (fixed layout) + trailing text + separator.
        postBackspaces(correction.coreKeys.count + correction.trailingText.count + 1)
        layouts.select(correction.originalLayout)
        usleep(layoutSettleMicroseconds)
        replay(correction.originalKeys)
        replay([correction.separator])
        dict.addException(correction.originalWord)
        log("Reverted \"\(correction.originalWord)\" — added to exceptions.txt.")
        reset()
    }

    // MARK: Synthetic events

    private func makeSource() -> CGEventSource? {
        let source = CGEventSource(stateID: .combinedSessionState)
        source?.userData = syntheticEventMarker
        return source
    }

    private func postBackspaces(_ count: Int) {
        guard count > 0, let source = makeSource() else { return }
        for _ in 0..<count {
            postKey(51, flags: [], source: source)
        }
    }

    private func replay(_ keys: [Key]) {
        guard let source = makeSource() else { return }
        for key in keys {
            postKey(key.code, flags: key.shift ? .maskShift : [], source: source)
        }
    }

    /// Types literal characters as unicode events — layout-independent, used
    /// for word-final punctuation whose keycode means something else in the
    /// layout we just switched to.
    private func typeText(_ text: String) {
        guard !text.isEmpty, let source = makeSource() else { return }
        for unit in Array(text.utf16) {
            var utf16Unit = unit
            for isDown in [true, false] {
                guard let event = CGEvent(keyboardEventSource: source,
                                          virtualKey: 0, keyDown: isDown) else { continue }
                event.keyboardSetUnicodeString(stringLength: 1, unicodeString: &utf16Unit)
                event.post(tap: .cghidEventTap)
            }
            usleep(keystrokeGapMicroseconds)
        }
    }

    private func postKey(_ code: CGKeyCode, flags: CGEventFlags, source: CGEventSource) {
        for isDown in [true, false] {
            guard let event = CGEvent(keyboardEventSource: source,
                                      virtualKey: code, keyDown: isDown) else { continue }
            event.flags = flags
            event.post(tap: .cghidEventTap)
        }
        usleep(keystrokeGapMicroseconds)
    }
}

// MARK: - Auto-update

/// Updates from GitHub Releases of the public mirror (arolus/translit).
/// CI builds Translit.app there for every new VERSION; the app checks
/// releases/latest at startup and every 6 hours, downloads the zip asset and
/// swaps ~/Applications/Translit.app — no toolchain needed on this machine.
///
/// After an update macOS asks for Accessibility again: the ad-hoc signature
/// identity changes with every binary, so the stale TCC entry is reset
/// deliberately (it would look enabled while not working). The app polls and
/// picks the permission up as soon as it is granted.
final class Updater {
    static let releasesRepo = "arolus/translit"

    /// Latest version seen on GitHub — lets the menu offer "Обновить до X".
    private(set) static var latestKnown: String?

    private var timer: Timer?
    private var busy = false

    func start() {
        // "dev" = running straight from .build, not from an installed bundle —
        // nothing to meaningfully update.
        guard appVersion != "dev" else { return }
        DispatchQueue.main.asyncAfter(deadline: .now() + 30) { [weak self] in
            self?.checkAndApply()
        }
        let t = Timer.scheduledTimer(withTimeInterval: 6 * 3600, repeats: true) { [weak self] _ in
            self?.checkAndApply()
        }
        t.tolerance = 1800 // battery-friendly: let the system coalesce wakeups
        timer = t
    }

    struct Release {
        let version: String
        let zipURL: URL
    }

    /// Stops URLSession at the first redirect so the Location header is ours.
    private final class RedirectCatcher: NSObject, URLSessionTaskDelegate {
        func urlSession(_ session: URLSession, task: URLSessionTask,
                        willPerformHTTPRedirection response: HTTPURLResponse,
                        newRequest request: URLRequest,
                        completionHandler: @escaping (URLRequest?) -> Void) {
            completionHandler(nil)
        }
    }

    /// Resolves the latest release WITHOUT the GitHub API: unauthenticated
    /// API calls are limited to 60/hr per IP, which a busy or shared address
    /// exhausts. /releases/latest answers with a redirect to .../tag/vX.Y.Z —
    /// the version is read from the Location header, and the asset URL is
    /// deterministic. Completion runs on a URLSession queue.
    static func fetchLatest(completion: @escaping (Release?, String?) -> Void) {
        let url = URL(string: "https://github.com/\(releasesRepo)/releases/latest")!
        let session = URLSession(configuration: .ephemeral,
                                 delegate: RedirectCatcher(), delegateQueue: nil)
        var request = URLRequest(url: url)
        request.timeoutInterval = 30
        let task = session.dataTask(with: request) { _, response, error in
            defer { session.finishTasksAndInvalidate() }
            if let error = error {
                completion(nil, error.localizedDescription)
                return
            }
            guard let http = response as? HTTPURLResponse,
                  (300..<400).contains(http.statusCode),
                  let location = http.value(forHTTPHeaderField: "Location"),
                  let tag = URL(string: location)?.lastPathComponent,
                  tag.hasPrefix("v"), tag.contains(".") else {
                let code = (response as? HTTPURLResponse)?.statusCode ?? 0
                completion(nil, "no releases found (HTTP \(code))")
                return
            }
            let version = String(tag.dropFirst())
            let zip = URL(string: "https://github.com/\(releasesRepo)" +
                                  "/releases/download/\(tag)/Translit.app.zip")!
            DispatchQueue.main.async { latestKnown = version }
            completion(Release(version: version, zipURL: zip), nil)
        }
        task.resume()
    }

    /// Numeric component-wise comparison: "0.2.10" > "0.2.9".
    static func isNewer(_ a: String, than b: String) -> Bool {
        let av = a.split(separator: ".").map { Int($0) ?? 0 }
        let bv = b.split(separator: ".").map { Int($0) ?? 0 }
        for i in 0..<max(av.count, bv.count) {
            let x = i < av.count ? av[i] : 0
            let y = i < bv.count ? bv[i] : 0
            if x != y { return x > y }
        }
        return false
    }

    /// force = the user clicked the menu item: every outcome must be visible,
    /// not just logged (the log is invisible outside launchd runs).
    func checkAndApply(force: Bool = false) {
        guard force || Settings.autoUpdate else { return }
        guard !busy else {
            if force { Updater.alert("Обновление уже выполняется.") }
            return
        }
        busy = true
        Updater.fetchLatest { [weak self] release, problem in
            DispatchQueue.main.async {
                guard let self = self else { return }
                guard let release = release else {
                    self.busy = false
                    log("Update check failed: \(problem ?? "unknown")")
                    if force {
                        Updater.alert("Не удалось проверить обновления: " +
                                      "\(problem ?? "неизвестная ошибка").")
                    }
                    return
                }
                guard Updater.isNewer(release.version, than: appVersion) else {
                    self.busy = false
                    log("Update check: \(appVersion) is current (latest \(release.version)).")
                    if force {
                        Updater.alert("Версия \(appVersion) — актуальная " +
                                      "(последний релиз \(release.version)).")
                    }
                    return
                }
                log("Update \(appVersion) → \(release.version): downloading…")
                if force {
                    Updater.alert("Обновляюсь: \(appVersion) → \(release.version).\n" +
                                  "Приложение перезапустится само, после чего macOS " +
                                  "заново спросит права Accessibility.")
                }
                DispatchQueue.global(qos: .utility).async {
                    self.performUpdate(release, verbose: force)
                    DispatchQueue.main.async { self.busy = false }
                }
            }
        }
    }

    /// Modal alert on the main thread; used only for user-initiated actions.
    static func alert(_ message: String) {
        let show = {
            NSApp.activate(ignoringOtherApps: true)
            let alert = NSAlert()
            alert.messageText = "Translit"
            alert.informativeText = message
            alert.runModal()
        }
        if Thread.isMainThread { show() } else { DispatchQueue.main.async(execute: show) }
    }

    /// Background thread: download the zip, unpack, swap the installed app.
    private func performUpdate(_ release: Release, verbose: Bool) {
        func fail(_ message: String) {
            log("⚠️ \(message)")
            if verbose { Updater.alert(message) }
        }

        let sem = DispatchSemaphore(value: 0)
        var zipData: Data?
        var downloadProblem: String?
        URLSession.shared.dataTask(with: release.zipURL) { data, _, error in
            zipData = data
            downloadProblem = error?.localizedDescription
            sem.signal()
        }.resume()
        sem.wait()
        guard let data = zipData else {
            fail("Не удалось скачать обновление: \(downloadProblem ?? "нет данных").")
            return
        }

        let fm = FileManager.default
        let tmpDir = NSTemporaryDirectory() + "translit-update-\(release.version)"
        let zipPath = tmpDir + "/Translit.app.zip"
        try? fm.removeItem(atPath: tmpDir)
        do {
            try fm.createDirectory(atPath: tmpDir, withIntermediateDirectories: true)
            try data.write(to: URL(fileURLWithPath: zipPath))
        } catch {
            fail("Не удалось сохранить обновление: \(error.localizedDescription)")
            return
        }
        guard runProcess("/usr/bin/ditto", ["-x", "-k", zipPath, tmpDir]) == 0 else {
            fail("Не удалось распаковать обновление.")
            return
        }
        let newApp = tmpDir + "/Translit.app"
        guard fm.isExecutableFile(atPath: newApp + "/Contents/MacOS/translit") else {
            fail("В архиве релиза нет Translit.app.")
            return
        }
        // System-wide /Applications so the app shows up where people look;
        // ~/Applications only when /Applications isn't writable. A stale copy
        // at the other location is removed (migration from older versions).
        let homeInstall = NSHomeDirectory() + "/Applications/Translit.app"
        let dst = fm.isWritableFile(atPath: "/Applications")
            ? "/Applications/Translit.app" : homeInstall
        do {
            try fm.createDirectory(atPath: (dst as NSString).deletingLastPathComponent,
                                   withIntermediateDirectories: true)
            if fm.fileExists(atPath: dst) { try fm.removeItem(atPath: dst) }
            try fm.moveItem(atPath: newApp, toPath: dst)
        } catch {
            fail("Не удалось установить обновление: \(error.localizedDescription)")
            return
        }
        try? fm.removeItem(atPath: tmpDir)
        if dst != homeInstall { try? fm.removeItem(atPath: homeInstall) }

        let lsregister = "/System/Library/Frameworks/CoreServices.framework/Frameworks/" +
                         "LaunchServices.framework/Support/lsregister"
        if fm.isExecutableFile(atPath: lsregister) { runProcess(lsregister, ["-f", dst]) }
        // The old TCC entry points at the previous binary — reset so the fresh
        // one can raise the system prompt instead of silently not working.
        runProcess("/usr/bin/tccutil", ["reset", "Accessibility", bundleID])
        // Keep the login agent pointing at the fresh binary (the install may
        // have just migrated between Applications folders).
        if Autostart.enabled {
            Autostart.writePlist(binary: dst + "/Contents/MacOS/translit")
        }

        log("Updated to \(release.version), restarting…")
        // Relaunch from the new location — works for launchd and manual runs
        // alike. The detached shell survives our exit; the delay lets the
        // singleton lock go free.
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/bin/sh")
        proc.arguments = ["-c", "sleep 1; /usr/bin/open -a '\(dst)'"]
        try? proc.run()
        DispatchQueue.main.async { NSApp.terminate(nil) }
    }

    @discardableResult
    private func runProcess(_ path: String, _ args: [String], cwd: String? = nil) -> Int32 {
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: path)
        proc.arguments = args
        if let cwd = cwd { proc.currentDirectoryURL = URL(fileURLWithPath: cwd) }
        do { try proc.run() } catch { return -1 }
        proc.waitUntilExit()
        return proc.terminationStatus
    }
}

// MARK: - Autostart

/// Login autostart via a LaunchAgent plist (SMAppService needs a Team ID
/// signature; the plist route works for ad-hoc tools, same as the other
/// dotfiles utilities). Enabling writes the plist — launchd picks it up at
/// the next login, the app is already running now. Disabling removes it;
/// the current instance keeps running.
enum Autostart {
    static let plistPath = NSHomeDirectory() + "/Library/LaunchAgents/\(bundleID).plist"

    static var enabled: Bool { FileManager.default.fileExists(atPath: plistPath) }

    /// Binary the agent should launch: the bundle we are running from, or an
    /// installed copy when running unbundled (straight from .build).
    static var launchBinary: String? {
        if Bundle.main.bundleURL.pathExtension == "app" {
            return Bundle.main.bundleURL
                .appendingPathComponent("Contents/MacOS/translit").path
        }
        for dir in ["/Applications", NSHomeDirectory() + "/Applications"] {
            let bin = dir + "/Translit.app/Contents/MacOS/translit"
            if FileManager.default.isExecutableFile(atPath: bin) { return bin }
        }
        return nil
    }

    static func toggle() {
        if enabled { disable() } else { enable() }
    }

    static func enable() {
        guard let binary = launchBinary else {
            log("⚠️ Autostart: no installed Translit.app found.")
            return
        }
        writePlist(binary: binary)
        log("Autostart enabled (\(binary)).")
    }

    static func disable() {
        try? FileManager.default.removeItem(atPath: plistPath)
        log("Autostart disabled.")
    }

    /// (Re)writes the LaunchAgent plist. Also called after updates so the
    /// agent always points at the current binary location.
    static func writePlist(binary: String) {
        let logs = NSHomeDirectory() + "/Library/Logs"
        let plist = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>Label</key>
            <string>\(bundleID)</string>
            <key>ProgramArguments</key>
            <array>
                <string>\(binary)</string>
            </array>
            <key>RunAtLoad</key>
            <true/>
            <key>KeepAlive</key>
            <false/>
            <key>StandardOutPath</key>
            <string>\(logs)/translit.out.log</string>
            <key>StandardErrorPath</key>
            <string>\(logs)/translit.err.log</string>
            <key>ProcessType</key>
            <string>Interactive</string>
        </dict>
        </plist>
        """
        let fm = FileManager.default
        try? fm.createDirectory(atPath: (plistPath as NSString).deletingLastPathComponent,
                                withIntermediateDirectories: true)
        try? fm.createDirectory(atPath: logs, withIntermediateDirectories: true)
        try? plist.write(toFile: plistPath, atomically: true, encoding: .utf8)
    }
}

// MARK: - Accessibility

enum Accessibility {
    static var isTrusted: Bool { AXIsProcessTrusted() }

    @discardableResult
    static func request() -> Bool {
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true]
        return AXIsProcessTrustedWithOptions(options as CFDictionary)
    }
}

// MARK: - Dictionary window

/// Rules & exceptions editor: a table of words with a live preview of what
/// each becomes on the other layout, add/remove controls. Writes go straight
/// to the same text files, so hand edits and git sync keep working; the file
/// watcher refreshes the table if the files change under us.
final class DictionaryWindowController: NSObject, NSWindowDelegate,
                                        NSTableViewDataSource, NSTableViewDelegate {
    private let dict: UserDict
    private let layouts: Layouts
    private var window: NSWindow!
    private let segmented = NSSegmentedControl(
        labels: ["Правила", "Исключения"], trackingMode: .selectOne,
        target: nil, action: nil)
    private let infoLabel = NSTextField(wrappingLabelWithString: "")
    private let table = NSTableView()
    private let addField = NSTextField()
    private let addButton = NSButton(title: "Добавить", target: nil, action: nil)
    private let removeButton = NSButton(title: "Удалить", target: nil, action: nil)
    private var words: [String] = []

    private var showingRules: Bool { segmented.selectedSegment == 0 }

    init(dict: UserDict, layouts: Layouts) {
        self.dict = dict
        self.layouts = layouts
        super.init()
        buildWindow()
        dict.onChange = { [weak self] in self?.reloadData() }
    }

    func show() {
        reloadData()
        NSApp.activate(ignoringOtherApps: true)
        window.center()
        window.makeKeyAndOrderFront(nil)
        window.makeFirstResponder(addField)
    }

    // MARK: Layout

    private func buildWindow() {
        window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 440, height: 520),
                          styleMask: [.titled, .closable],
                          backing: .buffered, defer: false)
        window.title = "Словарь Translit"
        window.delegate = self
        window.isReleasedWhenClosed = false

        segmented.target = self
        segmented.action = #selector(tabChanged)
        segmented.selectedSegment = 0

        infoLabel.font = .systemFont(ofSize: 11)
        infoLabel.textColor = .secondaryLabelColor
        infoLabel.preferredMaxLayoutWidth = 392

        let wordColumn = NSTableColumn(identifier: .init("word"))
        wordColumn.title = "Набрано"
        wordColumn.width = 170
        let becomesColumn = NSTableColumn(identifier: .init("becomes"))
        becomesColumn.title = "Станет"
        becomesColumn.width = 170
        table.addTableColumn(wordColumn)
        table.addTableColumn(becomesColumn)
        table.dataSource = self
        table.delegate = self
        table.allowsMultipleSelection = true
        table.usesAlternatingRowBackgroundColors = true

        let scroll = NSScrollView()
        scroll.documentView = table
        scroll.hasVerticalScroller = true
        scroll.borderType = .bezelBorder
        scroll.translatesAutoresizingMaskIntoConstraints = false
        scroll.heightAnchor.constraint(equalToConstant: 300).isActive = true

        addField.placeholderString = "слово: в, так, the…"
        addField.font = .systemFont(ofSize: 13)
        addField.target = self
        addField.action = #selector(addClicked) // Enter in the field adds
        addButton.target = self
        addButton.action = #selector(addClicked)
        addButton.bezelStyle = .rounded
        addButton.setContentHuggingPriority(.required, for: .horizontal)
        let addRow = NSStackView(views: [addField, addButton])
        addRow.orientation = .horizontal
        addRow.spacing = 8

        removeButton.target = self
        removeButton.action = #selector(removeClicked)
        removeButton.bezelStyle = .rounded
        removeButton.isEnabled = false
        let fileButton = NSButton(title: "Открыть файл…", target: self,
                                  action: #selector(openFileClicked))
        fileButton.bezelStyle = .rounded
        let bottomRow = NSStackView(views: [removeButton, NSView(), fileButton])
        bottomRow.orientation = .horizontal

        let stack = NSStackView(views: [segmented, infoLabel, scroll, addRow, bottomRow])
        stack.orientation = .vertical
        stack.alignment = .leading
        stack.spacing = 10
        stack.translatesAutoresizingMaskIntoConstraints = false

        let content = window.contentView!
        content.addSubview(stack)
        NSLayoutConstraint.activate([
            stack.leadingAnchor.constraint(equalTo: content.leadingAnchor, constant: 20),
            stack.trailingAnchor.constraint(equalTo: content.trailingAnchor, constant: -20),
            stack.topAnchor.constraint(equalTo: content.topAnchor, constant: 16),
            stack.bottomAnchor.constraint(equalTo: content.bottomAnchor, constant: -16),
            scroll.widthAnchor.constraint(equalTo: stack.widthAnchor),
            addRow.widthAnchor.constraint(equalTo: stack.widthAnchor),
            bottomRow.widthAnchor.constraint(equalTo: stack.widthAnchor),
            infoLabel.widthAnchor.constraint(equalTo: stack.widthAnchor),
        ])
    }

    // MARK: Data

    private func reloadData() {
        words = (showingRules ? dict.rules : dict.exceptions).sorted()
        let base = showingRules
            ? "Настоящие слова, которые всегда восстанавливаются из опечатки: "
              + "кириллические — en→ru («и» ← \"b\"), латинские — ru→en (\"the\" ← «еру»)."
            : "Не исправляются никогда (как набрано). Backspace сразу после "
              + "автозамены отменяет её и добавляет слово сюда."
        // Name the storage: an unwritable file is why edits "don't stick".
        infoLabel.stringValue = dict.storageIsWritable
            ? base
            : base + "\n⚠️ Файл \(UserDict.dirPath) недоступен для записи — правки не сохранятся."
        table.tableColumns[0].title = showingRules ? "Слово" : "Как набрано"
        table.tableColumns[1].title = showingRules ? "Опечатка в чужой раскладке" : "В другой раскладке"
        table.reloadData()
        removeButton.isEnabled = false
    }

    func numberOfRows(in tableView: NSTableView) -> Int { words.count }

    func tableView(_ tableView: NSTableView, viewFor tableColumn: NSTableColumn?,
                   row: Int) -> NSView? {
        let word = words[row]
        let isWordColumn = tableColumn?.identifier.rawValue == "word"
        let text = isWordColumn ? word : layouts.converted(word)
        let id = NSUserInterfaceItemIdentifier("cell")
        let label = (tableView.makeView(withIdentifier: id, owner: nil) as? NSTextField)
            ?? {
                let l = NSTextField(labelWithString: "")
                l.identifier = id
                l.font = .systemFont(ofSize: 13)
                return l
            }()
        label.stringValue = text
        label.textColor = isWordColumn ? .labelColor : .secondaryLabelColor
        return label
    }

    func tableViewSelectionDidChange(_ notification: Notification) {
        removeButton.isEnabled = !table.selectedRowIndexes.isEmpty
    }

    // MARK: Actions

    @objc private func tabChanged() { reloadData() }

    @objc private func addClicked() {
        let word = addField.stringValue.trimmingCharacters(in: .whitespaces).lowercased()
        guard !word.isEmpty, !word.contains(" "), !word.hasPrefix("#") else { return }
        if showingRules { dict.addRule(word) } else { dict.addException(word) }
        addField.stringValue = ""
        // Show the freshly added word (onChange has already reloaded the table).
        if let row = words.firstIndex(of: word) {
            table.scrollRowToVisible(row)
            table.selectRowIndexes([row], byExtendingSelection: false)
        }
    }

    @objc private func removeClicked() {
        let selected = table.selectedRowIndexes.map { words[$0] }
        for word in selected {
            if showingRules { dict.removeRule(word) } else { dict.removeException(word) }
        }
    }

    @objc private func openFileClicked() {
        let path = showingRules ? UserDict.rulesPath : UserDict.exceptionsPath
        NSWorkspace.shared.open(URL(fileURLWithPath: path))
    }
}

// MARK: - Status bar

final class StatusBarController: NSObject, NSMenuDelegate {
    private let item = NSStatusBar.system.statusItem(withLength: NSStatusItem.squareLength)
    private let engine: Engine?
    private let updater: Updater?
    private let startupProblem: String?

    init(engine: Engine?, updater: Updater?, startupProblem: String?) {
        self.engine = engine
        self.updater = updater
        self.startupProblem = startupProblem
        super.init()
        let menu = NSMenu()
        menu.delegate = self
        item.menu = menu
        item.button?.toolTip = "Translit — автопереключение раскладки"
        refreshIcon()
    }

    /// Plain keyboard when healthy; a badged one when something blocks
    /// corrections (missing Accessibility, suspended tap) so the problem is
    /// visible without opening the menu. Dimmed (the system "disabled" look)
    /// when corrections are off on purpose — globally or for the frontmost
    /// app — so a glance tells why nothing is being fixed here.
    func refreshIcon() {
        guard let button = item.button else { return }
        let problem = engine == nil || !Accessibility.isTrusted || engine?.tapSuspended == true
        let names = problem
            ? ["keyboard.badge.ellipsis", "exclamationmark.triangle"]
            : ["keyboard"]
        let cfg = NSImage.SymbolConfiguration(pointSize: 15, weight: .medium)
        if let base = names.lazy.compactMap({
            NSImage(systemSymbolName: $0, accessibilityDescription: "Translit")
        }).first {
            let img = base.withSymbolConfiguration(cfg) ?? base
            img.isTemplate = true
            button.image = img
        } else {
            button.title = problem ? "Тр!" : "Тр"
        }

        let frontID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? ""
        button.appearsDisabled = !Settings.enabled || Settings.excludedApps.contains(frontID)
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        menu.removeAllItems()
        refreshIcon()

        // Engine health first: secure input or a suspended tap explain
        // "перестало работать" better than silence.
        if let status = engine?.currentStatus() {
            menu.addItem(NSMenuItem(title: status, action: nil, keyEquivalent: ""))
            if engine?.tapSuspended == true {
                let revive = NSMenuItem(title: "Возобновить перехват сейчас",
                                        action: #selector(reviveTapClicked), keyEquivalent: "")
                revive.target = self
                menu.addItem(revive)
            }
            menu.addItem(.separator())
        }

        // Accessibility state is checked live: the warning disappears from the
        // menu as soon as the permission is granted.
        let problem = startupProblem
            ?? (Accessibility.isTrusted ? nil : "Нет прав Accessibility — выдайте в Настройках")
        if let problem = problem {
            menu.addItem(NSMenuItem(title: problem, action: nil, keyEquivalent: ""))
            menu.addItem(.separator())
        } else {
            let toggle = NSMenuItem(title: "Включено",
                                    action: #selector(toggleEnabled), keyEquivalent: "")
            toggle.target = self
            toggle.state = Settings.enabled ? .on : .off
            menu.addItem(toggle)

            if let front = NSWorkspace.shared.frontmostApplication,
               let id = front.bundleIdentifier {
                let excluded = Settings.excludedApps.contains(id)
                let title = excluded
                    ? "Включить в «\(front.localizedName ?? id)»"
                    : "Отключить в «\(front.localizedName ?? id)»"
                let appItem = NSMenuItem(title: title,
                                         action: #selector(toggleFrontApp), keyEquivalent: "")
                appItem.target = self
                appItem.representedObject = id
                menu.addItem(appItem)
            }
            menu.addItem(.separator())

            let sound = NSMenuItem(title: "Звук при исправлении",
                                   action: #selector(toggleSound), keyEquivalent: "")
            sound.target = self
            sound.state = Settings.soundOnFix ? .on : .off
            menu.addItem(sound)

            menu.addItem(.separator())

            // The rule count doubles as a health check: "0 правил" says the
            // dictionary never loaded, which looks the same from the outside
            // as corrections not working.
            let ruleCount = engine?.dict.rules.count ?? 0
            let dictionary = NSMenuItem(title: "Словарь… (\(ruleCount) правил)",
                                        action: #selector(openDictionary), keyEquivalent: "d")
            dictionary.target = self
            menu.addItem(dictionary)

            menu.addItem(.separator())
            let hint = NSMenuItem(title: "Backspace сразу после исправления — отмена",
                                  action: nil, keyEquivalent: "")
            hint.isEnabled = false
            menu.addItem(hint)
            menu.addItem(.separator())
        }

        if updater != nil, appVersion != "dev" {
            let login = NSMenuItem(title: "Запускать при входе",
                                   action: #selector(toggleAutostart), keyEquivalent: "")
            login.target = self
            login.state = Autostart.enabled ? .on : .off
            login.isEnabled = Autostart.launchBinary != nil
            menu.addItem(login)

            let auto = NSMenuItem(title: "Автообновление",
                                  action: #selector(toggleAutoUpdate), keyEquivalent: "")
            auto.target = self
            auto.state = Settings.autoUpdate ? .on : .off
            menu.addItem(auto)

            let latest = Updater.latestKnown
            let updatable = latest.map { Updater.isNewer($0, than: appVersion) } ?? false
            let title = updatable
                ? "Обновить до \(latest!)"
                : "Проверить обновления"
            let check = NSMenuItem(title: title,
                                   action: #selector(checkUpdates), keyEquivalent: "")
            check.target = self
            menu.addItem(check)
            menu.addItem(.separator())
        }

        menu.addItem(NSMenuItem(title: "Translit \(appVersion)", action: nil, keyEquivalent: ""))
        menu.addItem(NSMenuItem(title: "Выход",
                                action: #selector(NSApplication.terminate(_:)), keyEquivalent: "q"))
    }

    @objc private func toggleEnabled() {
        Settings.enabled.toggle()
        refreshIcon()
    }

    @objc private func toggleSound() {
        Settings.soundOnFix.toggle()
    }

    @objc private func toggleAutoUpdate() {
        Settings.autoUpdate.toggle()
    }

    @objc private func toggleAutostart() {
        Autostart.toggle()
    }

    @objc private func reviveTapClicked() {
        engine?.reviveTap()
    }

    @objc private func checkUpdates() {
        updater?.checkAndApply(force: true)
    }

    private lazy var dictionaryWindow: DictionaryWindowController? = {
        guard let engine = engine else { return nil }
        return DictionaryWindowController(dict: engine.dict, layouts: engine.layouts)
    }()

    @objc private func openDictionary() {
        dictionaryWindow?.show()
    }

    @objc private func toggleFrontApp(_ sender: NSMenuItem) {
        guard let id = sender.representedObject as? String else { return }
        var excluded = Settings.excludedApps
        if excluded.contains(id) { excluded.remove(id) } else { excluded.insert(id) }
        Settings.excludedApps = excluded
        refreshIcon()
    }
}

// MARK: - App delegate

final class AppDelegate: NSObject, NSApplicationDelegate {
    private var statusBar: StatusBarController?
    private var accessibilityRetryTimer: Timer?
    private let updater = Updater()

    func applicationDidFinishLaunching(_ notification: Notification) {
        updater.start()

        guard let layouts = Layouts() else {
            statusBar = StatusBarController(
                engine: nil, updater: updater,
                startupProblem: "Русская раскладка не включена в системе")
            return
        }
        let engine = Engine(layouts: layouts)
        Engine.shared = engine

        if Accessibility.isTrusted {
            startEngine(engine)
        } else {
            log("Waiting for Accessibility permission…")
            Accessibility.request()
            // Poll until granted, then create the tap and stop polling.
            accessibilityRetryTimer = Timer.scheduledTimer(withTimeInterval: 3, repeats: true) {
                [weak self] timer in
                guard Accessibility.isTrusted else { return }
                timer.invalidate()
                self?.accessibilityRetryTimer = nil
                self?.startEngine(engine)
                self?.statusBar?.refreshIcon()
            }
        }
        statusBar = StatusBarController(engine: engine, updater: updater, startupProblem: nil)
        engine.onStateChange = { [weak self] in self?.statusBar?.refreshIcon() }
    }

    private func startEngine(_ engine: Engine) {
        if !engine.start() {
            log("⚠️ Could not create the event tap (Accessibility missing?).")
        }
    }
}

// MARK: - Entry point

let args = CommandLine.arguments
if args.contains("--version") {
    print("translit \(appVersion)")
    exit(0)
}

// Debug: score a word through both layout readings without installing.
// Example: translit --test ghbdtn   → shows both readings and the verdict.
if let flagIndex = args.firstIndex(of: "--test"), flagIndex + 1 < args.count {
    guard let layouts = Layouts() else { exit(1) }
    let word = args[flagIndex + 1].lowercased()

    var keycodeFor: [Character: CGKeyCode] = [:]
    for code in 0..<128 {
        if let ch = layouts.enChars[code] { keycodeFor[ch] = keycodeFor[ch] ?? CGKeyCode(code) }
        if let ch = layouts.ruChars[code] { keycodeFor[ch] = keycodeFor[ch] ?? CGKeyCode(code) }
    }
    var codes: [CGKeyCode] = []
    for ch in word {
        guard let code = keycodeFor[ch] else {
            print("no key produces \"\(ch)\" in either layout")
            exit(1)
        }
        codes.append(code)
    }

    let enScore = scoreReading(codes, letterIndex: layouts.enLetterIndex,
                               table: enBigrams, n: enAlphabet.count + 1)
    let ruScore = scoreReading(codes, letterIndex: layouts.ruLetterIndex,
                               table: ruBigrams, n: ruAlphabet.count + 1)
    let render = { (map: [Character?]) in String(codes.compactMap { map[Int($0)] }) }
    let fmt = { (s: Double?) in s.map { String(format: "%.2f", $0) } ?? "impossible" }
    print("en reading: \"\(render(layouts.enChars))\"  score \(fmt(enScore))")
    print("ru reading: \"\(render(layouts.ruChars))\"  score \(fmt(ruScore))")

    // Run the ENGINE's own decision for both layouts — what would happen if
    // these keys were typed with en active, and with ru active.
    let engine = Engine(layouts: layouts)
    let keys = codes.map { Key(code: $0, shift: false) }
    let space = Key(code: 49, shift: false)
    print("")
    for current in [Layouts.Current.en, Layouts.Current.ru] {
        let typed = current == .en ? render(layouts.enChars) : render(layouts.ruChars)
        var why = ""
        let verdict = engine.decide(word: keys, separator: space, current: current) { why = $0 }
        let name = current == .en ? "en" : "ru"
        if let verdict = verdict {
            let fixed = current == .en ? render(layouts.ruChars) : render(layouts.enChars)
            print("typed with \(name) active → \"\(typed)\" IS FIXED to " +
                  "\"\(fixed)\(verdict.trailingText)\"  (\(why))")
        } else {
            print("typed with \(name) active → \"\(typed)\" is left alone  (\(why))")
        }
    }
    if let en = enScore, let ru = ruScore {
        let gap = abs(en - ru)
        let winner = en > ru ? "en" : "ru"
        print("verdict: \(winner) wins by \(String(format: "%.2f", gap)) " +
              "(margin \(switchMargin), floor \(plausibilityFloor))")
    } else {
        print("verdict: \(enScore != nil ? "en" : (ruScore != nil ? "ru" : "neither")) " +
              "is the only possible reading")
    }
    exit(0)
}

guard acquireSingletonLock() else {
    log("Another instance is running — exiting.")
    exit(0)
}

let app = NSApplication.shared
app.setActivationPolicy(.accessory)
let delegate = AppDelegate()
app.delegate = delegate
app.run()
